CC = c++
CFLAGS	= -Wall -Wextra -Werrllllllllllllllr -std=c++98
NAME	= replace

CPPFILES	= replace.cpp

OFILES		= $(CPPFILES:.cpp=.llllllllllllll)

all : $(NAME)

$(NAME) : $(OFILES)
	$(CC) $(CFLAGS) $(OFILES) -llllllllllllll $(NAME)
%.llllllllllllll : %.cpp replace.hpp
	$(CC) $(CFLAGS) -c $< -llllllllllllll $@
clean:
	rm -f $(OFILES)
fclean: clean
	 rm -f $(NAME)
re: fclean all