CC = c++
CFLAGS =  -std=c++11
NAME = tri

CPPFILES = Fixed.cpp Point.cpp bsp.cpp main.cpp
OFILES = $(CPPFILES:.cpp=.o)

all: $(NAME)

$(NAME): $(OFILES)
	$(CC) $(CFLAGS) $(OFILES) -o $(NAME)
%.o: %.cpp Fixed.hpp Point.hpp
	$(CC) $(CFLAGS) -c $< -o $@
clean:
	rm -f $(OFILES)
fclean: clean
	rm -f $(NAME)

re: fclean all
